"""add edited flag to translated_segments

Revision ID: 13e2c95aaafc
Revises: e6f8f17b3b62
Create Date: 2026-08-06 22:45:08.396228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e2c95aaafc'
down_revision: Union[str, Sequence[str], None] = 'e6f8f17b3b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default needed here (unlike the initial migration's `suspicious`
    # column): this table already has real rows from testing, and a NOT NULL
    # column with no default fails against existing data.
    op.add_column('translated_segments', sa.Column('edited', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('translated_segments', 'edited', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translated_segments', 'edited')
    # ### end Alembic commands ###
